#!/bin/bash
HTTPS=1 \
SSL_CERT='/etc/letsencrypt/live/codingjoa.kro.kr/cert.pem' \
SSL_KEY='/etc/letsencrypt/live/codingjoa.kro.kr/privkey.pem' \
JEKO_HOME=$HOME'/jeko' \
SESSION=true \
CORS_WHITELIST='.corsWhitelist' \
MARIADB_NAME=plant \
node .
