#!/bin/bash
PORT=49100 SESSION=true PROXY=true MARIADB_NAME=plant CORS_WHITELIST='.corsWhitelist' SSL_KEY='/etc/letsencrypt/live/codingjoa.kro.kr/privkey.pem' SSL_CERT='/etc/letsencrypt/live/codingjoa.kro.kr/cert.pem' JEKO_HOME=$HOME'/jeko' node .
